routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('layouts.master');
// });

Route::get('/', function() {
    return redirect(route('login'));
});

Route::group(['middleware' => 'auth'], function() {

    Route::get('/home', 'HomeController@index')->name('home');
    // Middleware berdasarkan role
    Route::group(['middleware' => ['role:admin']], function() {
        Route::prefix('admin')->group(function() {
            Route::resource('/role', 'RoleController')->except(['create', 'show', 'edit', 'update']);
            Route::resource('/user', 'UserController')->except(['show']);
            Route::post('/users/permission', 'UserController@addPermission')->name('user.add_permission');
            Route::get('/users/role-permission', 'UserController@rolePermission')->name('user.roles_permission');
            Route::put('/users/permission/{role}', 'UserController@setRolePermission')->name('user.setRolePermission');
            Route::get('/users/role/{role}', 'UserController@roles')->name('user.role');
            Route::put('/users/role/{role}', 'UserController@setRole')->name('user.set_role');
        });
    });
    


    // Middleware berdasarkan permission
    Route::group(['middleware' => ['permission:create_product|edit_product|delete_product']], function() {
        Route::resource('category', 'CategoryController')->except(['create', 'show']);
        Route::resource('product', 'ProductController');
    });

    // Middleware berdasarkan role
    Route::group(['middleware' => ['role:kasir']], function() {
        Route::get('/transaksi', 'OrderController@addOrder')->name('order.transaksi');
    });

    Route::post('/cart', 'OrderController@addToCart');
    Route::get('/cart', 'OrderController@getCart');
    Route::delete('/cart/{id}', 'OrderController@removeCart');
});


Auth::routes();

app/User.php
<?php

namespace App;

use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use DB;
use App\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('created_at', 'DESC')->paginate(10);

        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::orderBy('name', 'ASC')->get();

        return view('users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $this->validate($request, [
            'name' => 'required|string|max:100',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6',
            'role' => 'required|string|exists:roles,name'
        ]);

        $user = User::firstOrCreate(
            [
                'email' => $request->email // mengutamakan email, hanya boleh satu email dalam table users
            ], 
            [
                'name' => $request->name,
                'password' => bcrypt($request->password),
                'status' => true
            ]
        );

        $user->assignRole($request->role); // menggunakan function assignRole() dari library Spatie
        
        return redirect(route('user.index'))->with(['success' => 'User <strong>' . $user->name . '</strong> Ditambahkan']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);

        // return view('users.edit', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string|max:100',
            'email' => 'required|email|exists:users,email',
            'password' => 'nullable|min:6',
        ]);

        $user = User::findOrFail($id);

        // Jika password diisi berarti mau rubah password, 
        // Jika password tidak diisi berarti tidak rubah password, pake password yang lama
        $password = !empty($request->password) ? bcrypt($request->password) : $user->password;

        $user->update([
            'name' => $request->name,
            'password' => $password
        ]);

        return redirect(route('user.index'))->with(['success' => 'User <strong>' . $user->name . '</strong> Diperbaharui']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        
        return redirect()->back()->with(['success' => 'User <strong>' . $user->name . '</strong> Dihapus']);
    }

    public function rolePermission(Request $request) 
    {
        $role = $request->get('role'); // dapat dari role_permission.blade.php edit permission untuk role
        // dd($role);

        // Default, set dua buah variable dengan nilai null
        $permission = null;
        $hasPermission = null;

        // Mengambil data role
        $roles = Role::all()->pluck('name'); // return name saja fungsi dari pluck

        // Apabila parameter role terpenuhi
        if (!empty($role)) {
            // Select Role berdasarkan namenya, ini sejenis dengan find()
            $getRole = Role::findByName($role);

            // Query untuk mengambil permission yang telah dimiliki oleh role terkait
            $hasPermission = DB::table('role_has_permissions')
                ->select('permissions.name')
                ->join('permissions', 'role_has_permissions.permission_id', '=', 'permissions.id')
                ->where('role_id', $getRole->id)->get()->pluck('name')->all();
            
            // dd($hasPermission);

            // Mengambil data permission
            $permissions = Permission::all()->pluck('name');
        }

        return view('users.role_permission', compact('roles', 'permissions', 'hasPermission'));
    }

    public function addPermission(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|unique:permissions'
        ]);

        $permission = Permission::firstOrCreate([
            'name' => $request->name
        ]);

        return redirect()->back();
    }

    public function setRolePermission(Request $request, $role)
    {
        // Select role berdasarkan namanya
        $role = Role::findByName($role);

        // fungsi syncPermission akan menghapus semua permission yang dimiliki role tersebut,
        // kemudian di-assign kembali sehingga tidak terjadi duplicate data
        $role->syncPermissions($request->permission);

        return redirect()->back()->with(['success' => 'Permission sudah di set!']);
    }

    public function setRole(Request $request, $id)
    {
        $this->validate($request, [
            'role' => 'required'
        ]);

        $user = User::findOrFail($id);

        // fungsi syncRole akan menghapus semua role yang dimiliki,
        // kemudian di-assign kembali sehingga tidak terjadi duplicate data
        $user->syncRoles($request->role);

        return redirect()->back()->with(['success' => 'Role sudah di set!']);
    }

    public function roles(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $roles = Role::all()->pluck('name');

        return view('users.roles', compact('user', 'roles'));
    }
}

resources/views/users/create.blade.php
@extends('layouts.master')

@section('title', 'Tambah User')
@section('top-resource')

@endsection
@section('content')
<section class="content-header">
<h1>
    Tambah User
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Manajemen User</a></li>
    <li><a href="{{ route('user.index') }}">User</a></li>
    <li class="active">Tambah User</li>
</ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                @component('components.card')
                    @slot('header')
                        Tambah User
                    @endslot

                    <div class="box-body">
                        <form action="{{ route('user.store') }}" role="form" method="POST" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <div class="box-body">
                                @include('components.error')
                                @if(session('error'))
                                    @component('components.alert', ['type' => 'danger'])
                                        {!! session('error') !!}
                                    @endcomponent
                                @endif
                                <div class="form-group">
                                    <label for="name">Nama<sup>*</sup></label>
                                    <input type="text" name="name" id="name" required
                                    class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" 
                                    placeholder="Masukan nama.." value="{{ old('name') }}">
                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="email">Email<sup>*</sup></label>
                                    <input type="email" name="email" id="email" required
                                    class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" 
                                    placeholder="Masukan email.." value="{{ old('email') }}">
                                    <p class="text-danger">{{ $errors->first('email') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="password">Password<sup>*</sup></label>
                                    <input type="password" name="password" id="password" required
                                    class="form-control {{ $errors->has('password') ? 'is-invalid' : '' }}" 
                                    placeholder="Masukan password.." value="{{ old('password') }}">
                                    <p class="text-danger">{{ $errors->first('password') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="role">Role<sup>*</sup></label>
                                    <select name="role" id="role" required
                                    class="form-control {{ $errors->has('role') ? 'is-invalid' : '' }}" >
                                        <option value="">Pilih</option>
                                        @foreach($roles as $row)
                                            <option value="{{ $row->name }}">{{ ucfirst($row->name) }}</option>
                                        @endforeach
                                    </select>
                                    <p class="text-danger">{{ $errors->first('role') }}</p>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-send"></i> Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box-body -->
                @endcomponent
            </div>
        </div>
    </div>
</section>
@endsection
@section('bottom-resource')
@endsection

resources/views/users/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit User')
@section('top-resource')

@endsection
@section('content')
<section class="content-header">
<h1>
    Edit User
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Manajemen User</a></li>
    <li><a href="{{ route('user.index') }}">User</a></li>
    <li class="active">Edit User</li>
</ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                @component('components.card')
                    @slot('header')
                        Edit User
                    @endslot

                    <div class="box-body">
                        <form action="{{ route('user.update', $user->id) }}" role="form" method="POST" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <div class="box-body">
                                @include('components.error')
                                @if(session('error'))
                                    @component('components.alert', ['type' => 'danger'])
                                        {!! session('error') !!}
                                    @endcomponent
                                @endif
                                <div class="form-group">
                                    <label for="name">Nama<sup>*</sup></label>
                                    <input type="text" name="name" id="name"
                                    class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" 
                                    value="{{ $user->name }}">
                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input type="email" name="email" id="email" readonly
                                    class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" 
                                    value="{{ $user->email }}">
                                    {{-- <p class="text-danger">{{ $errors->first('email') }}</p> --}}
                                    <p class="text-warning">Email user tidak dapat diganti</p>
                                </div>
                                <div class="form-group">
                                    <label for="password">Password</label>
                                    <input type="password" name="password" id="password"
                                    class="form-control {{ $errors->has('password') ? 'is-invalid' : '' }}">
                                    <p class="text-danger">{{ $errors->first('password') }}</p>
                                    <p class="text-warning">Biarkan kosong, jika tidak ingin mengganti password</p>
                                </div>
                                <div class="form-group">
                                    <label for="role">Role</label>
                                    @foreach($user->getRoleNames() as $role)
                                        <input class="form-control" type="text" readonly value="{{ $role }}">
                                    @endforeach
                                    
                                    <p class="text-warning">Role tidak dapat diganti</p>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-send"></i> Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box-body -->
                @endcomponent
            </div>
        </div>
    </div>
</section>
@endsection
@section('bottom-resource')
@endsection

resources/views/users/index.blade.php
@extends('layouts.master')

@section('title', 'Tampilkan User')
@section('top-resource')

@endsection
@section('content')
<section class="content-header">
<h1>
    Dashboard
    <small>Control panel</small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Manajemen User</a></li>
    <li class="active">User</li>
</ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                @component('components.card')
                    @slot('header')
                        <a href="{{ route('user.create') }}" class="btn btn-primary btn-sm">
                            <i class="fa fa-plus"></i> Tambah User</a>
                    @endslot

                    <div class="box-body">
                        @if(session('success'))
                            @component('components.alert', ['type' => 'success'])
                                {!! session('success') !!}
                            @endcomponent
                        @endif
                        <table id="example" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th>Role</th>
                                    <th>Status</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php $no = 1; @endphp
                                @forelse($users as $row)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $row->name }}</td>
                                        <td>{{ $row->email }}</td>
                                        <td>
                                            @foreach($row->getRoleNames() as $role)
                                                <label class="label label-info">{{ $role }}</label>
                                            @endforeach
                                        </td>
                                        <td>
                                            @if($row->status)
                                                <label class="label label-success">Aktif</label>
                                            @else
                                                <label class="label label-default">Suspend</label>
                                            @endif
                                        </td>
                                        <td>
                                            <form action="{{ route('user.destroy', $row->id) }}" method="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                <a href="{{ route('user.role', $row->id) }}" class="btn btn-info btn-sm"><i class="fa fa-user-secret"></i></a>
                                                <a href="{{ route('user.edit', $row->id) }}" class="btn btn-warning btn-sm"><i class="fa fa-edit"></i></a>
                                                <button class="btn btn-danger btn-sm">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @empty
                                    <p colspan="6" class="text-center">Tidak Ada Data</p>
                                @endforelse
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th>Role</th>
                                    <th>Status</th>
                                    <th>Aksi</th>
                                </tr>
                            </tfoot>
                        </table>
                        <div class="pull-right">
                            {!! $users->links() !!}
                        </div>
                    </div>
                    <!-- /.box-body -->
                @endcomponent
            </div>
        </div>
    </div>
</section>
@endsection
@section('bottom-resource')
@endsection

resources/views/users/role_permission.blade.php
@extends('layouts.master')

@section('title', 'Role Permission')
@section('top-resource')
    <style type="text/css">
        .tab-pane{
            height:150px;
            overflow-y:scroll;
        }
    </style>
@endsection
@section('content')
<section class="content-header">
<h1>
    Permission
</h1>
<ol class="breadcrumb">
    <li><a href="{{ route('user.index') }}"><i class="fa fa-dashboard"></i> Manajemen User</a></li>
    <li class="active">Permission</li>
</ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-5">
                @component('components.card')
                    @slot('header')
                        Tambah Permission
                    @endslot

                    <form action="{{ route('user.add_permission') }}" role="form" method="POST">
                        {{ csrf_field() }}
                        <div class="box-body">
                            @include('components.error')
                            @if(session('error'))
                                @component('components.alert', ['type' => 'danger'])
                                    {!! session('error') !!}
                                @endcomponent
                            @endif
                            <div class="form-group">
                                <label for="name">Permission</label>
                                <input type="text" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" 
                                name="name" id="name" required
                                placeholder="Masukan permission.."
                                value="{{ old('name') }}">
                                <p class="text-danger">{{ $errors->first('name') }}</p>
                            </div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                @endcomponent
            </div>
            <div class="col-md-7">
                @component('components.card')
                    @slot('header')
                        Set Permission To Role
                    @endslot
                    @if(session('error'))
                        @component('components.alert', ['type' => 'success'])
                            {!! session('error') !!}
                        @endcomponent
                    @endif
                    {{-- Jika $permission bernilai kosong --}}
                    <form action="{{ route('user.roles_permission') }}" role="form" method="GET">
                        {{ csrf_field() }}
                        <div class="box-body">
                            <div class="form-group">
                                <label for="role">Role</label>
                                <select name="role" id="role"
                                class="form-control {{ $errors->has('role') ? 'is-invalid' : '' }}" >
                                    @foreach($roles as $value)
                                        <option value="{{ $value }}" {{ request()->get('role') == $value ? 'selected' : '' }}>{{ $value }}</option>
                                    @endforeach
                                </select>
                                <p class="text-danger">{{ $errors->first('role') }}</p>
                                <span class="input-group-btn">
                                    <button class="btn btn-danger">Check!</button>
                                </span>
                            </div>
                        </div>
                        <!-- /.box-body -->                        
                    </form>

                    {{-- Jika $permission bernilai tidak kosong --}}
                    @if(!empty($permissions))
                        <form action="{{ route('user.setRolePermission', request()->get('role')) }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <div class="form-group">
                                <div style="padding:10px;">
                                    <div class="nav nav-tabs-custom">
                                        <ul class="nav nav-tabs">
                                            <li class="active">
                                                <a href="#tab_1" data-toggle="tab">Permissions</a>
                                            </li>
                                        </ul>
                                        <div class="tab-content">
                                            <div class="tab-pane active" id="tab_1">
                                                @php $no = 1; @endphp
                                                @foreach($permissions as $key => $row)
                                                    <input type="checkbox" name="permission[]" 
                                                    class="minimal-red" 
                                                    value="{{ $row }}"
                                                    {{-- CEK, JIKA PERMISSION TERSEBUT SUDAH DI SET, MAKA CHECKED --}}
                                                    {{ in_array($row, $hasPermission) ? 'checked' : '' }}
                                                    > {{ $row }} <br>

                                                    @if($no++%4 == 0)
                                                        <br>
                                                    @endif
                                                @endforeach
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-send"></i> Set Permission</button>
                            </div>
                        </form>
                    @endif
                @endcomponent
            </div>
        </div>
    </div>
</section>
@endsection
@section('bottom-resource')
<script>
$(document).ready(function() {
    $('#example').DataTable();
} );
</script>
@endsection