routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('layouts.master');
// });

Route::get('/', function() {
    return redirect(route('login'));
});

Route::group(['middleware' => 'auth'], function() {

    Route::get('/home', 'HomeController@index')->name('home');
    // Middleware berdasarkan role
    Route::group(['middleware' => ['role:admin']], function() {
        Route::prefix('admin')->group(function() {
            Route::resource('/role', 'RoleController')->except(['create', 'show', 'edit', 'update']);
            Route::resource('/user', 'UserController')->except(['show']);
            Route::post('/users/permission', 'UserController@addPermission')->name('user.add_permission');
            Route::get('/users/role-permission', 'UserController@rolePermission')->name('user.roles_permission');
            Route::put('/users/permission/{role}', 'UserController@setRolePermission')->name('user.setRolePermission');
            Route::get('/users/role/{role}', 'UserController@roles')->name('user.role');
            Route::put('/users/role/{role}', 'UserController@setRole')->name('user.set_role');
        });
    });
    


    // Middleware berdasarkan permission
    Route::group(['middleware' => ['permission:create_product|edit_product|delete_product']], function() {
        Route::resource('category', 'CategoryController')->except(['create', 'show']);
        Route::resource('product', 'ProductController');
    });

    // Middleware berdasarkan role
    Route::group(['middleware' => ['role:kasir']], function() {
        Route::get('/transaksi', 'OrderController@addOrder')->name('order.transaksi');
    });

    Route::post('/cart', 'OrderController@addToCart');
    Route::get('/cart', 'OrderController@getCart');
    Route::delete('/cart/{id}', 'OrderController@removeCart');
});


Auth::routes();

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'code', 'name', 'description', 'stock', 'price', 'category_id', 'photo',
    ];

    // Jika tidak ingin pake $fillable bisa tuliskan ini
    // protected $guarded = [];

    public function category() {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use File;
use Image;
use App\Product;
use App\Category;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::with('category')->orderBy('created_at', 'DESC')->paginate();

        return view('products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::orderBy('name', 'ASC')->get();
        
        return view('products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validasi data
        $this->validate($request, [
            'code' =>  'required|string|max:10|unique:products', 
            'name' => 'required|string|max:100', 
            'description' => 'nullable|string|max:100', 
            'stock' => 'required|integer', 
            'price' => 'required|integer', 
            'category_id' => 'required|exists:categories,id',
            'photo' => 'nullable|image|mimes:jpg,png,jpeg'
        ]);

        try {
            // default $photo = null
            $photo = null;
            // jika terdapat file(foto/gambar) yang dikirim
            if ($request->hasFile('photo')) {
                // maka menjalankan method saveFile()
                $photo = $this->saveFile($request->name, $request->file('photo'));
            }

            // Simpan data ke dalam table products
            $product = Product::create([
                'code' => $request->code, 
                'name' => $request->name, 
                'description' => $request->description, 
                'stock' => $request->stock, 
                'price' => $request->price, 
                'category_id' => $request->category_id, 
                'photo' => $photo
            ]);

            return redirect(route('product.index'))
                ->with(['success' => '<strong>' . $product->name . '</strong> Ditambahkan']);
        } catch (\Exception $e) {
            // Jika gagal, kembali ke halaman sebelumnya kemudian menampilkan error
            return redirect()->back()->with(['error' => $e->getMessage()]);
        }
    }

    private function saveFile($name, $photo) {
        // set nama file adalah gabungan antara nama produk dan time(). Ekstensi gambar tetap dipertahankan
        $image = str_slug($name, '_') . time() . '.' . $photo->getClientOriginalExtension();

        $path = public_path('uploads/product');

        // Cek jika uploads/product bukan direktori / folder
        if (!File::isDirectory($path)) {
            // maka folder tersebut dibuat
            File::makeDirectory($path, 0777, true, true);
        }

        // Simpan gambar yang diupload ke dalam folder uplads/product
        Image::make($photo)->save($path . '/' . $image);

        // Mengembalikan nama file yang ditampung dalam variable $image
        return $image;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        $categories = Category::orderBy('name', 'ASC')->get();

        return view('products.edit', compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // validasi data
        $this->validate($request, [
            'code' =>  'required|string|max:10|exists:products,code', // mengecek apakah menggunakan code yang sama
            'name' => 'required|string|max:100', 
            'description' => 'nullable|string|max:100', 
            'stock' => 'required|integer', 
            'price' => 'required|integer', 
            'category_id' => 'required|exists:categories,id',
            'photo' => 'nullable|image|mimes:jpg,png,jpeg'
        ]);

        try {
            // query select berdasarkan id
            $product = Product::findOrFail($id);
            $photo = $product->photo;

            // cek jika ada file yang dikirim dari form
            if ($request->hasFile('photo')) {
                // cek jika photo tidak kosong maka file yang ada di folder uploads/product akan dihapus
                !empty($photo) ? File::delete(public_path('uploads/product/' . $product->photo)) : null;

                // uploading file photo yang baru menggunakan method saveFile() yang telah dibuat sebelumya
                $photo = $this->saveFile($request->name, $request->file('photo'));
            }

            // perbarui data di database
            $product->update([
                'name' => $request->name, 
                'description' => $request->description, 
                'stock' => $request->stock, 
                'price' => $request->price, 
                'category_id' => $request->category_id,
                'photo' => $photo
            ]);
            
            return redirect(route('product.index'))
                ->with(['success' => '<strong>' . $product->name . '</strong> Diperharui']);
        } catch (\Exception $e) {
            // Jika gagal, kembali ke halaman sebelumnya kemudian menampilkan error
            return redirect()->back()->with(['error' => $e->getMessage()]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // query select berdasarkan id
        $product = Product::findOrFail($id);

        // mengecek, jika field photo tidak null / kosong
        if(!empty($product->photo)) {
            // file akan dihapus dari folder uploads/product
            File::delete(public_path('uploads/product/' . $product->photo));
        }

        // hapus data dari table
        $product->delete();

        return redirect()->back()->with(['success' => '<strong>' . $product->name . '</strong> Telah Dihapus!']);
    }
}

resources/views/products/create.blade.php
@extends('layouts.master')

@section('title', 'Tambah Produk')
@section('top-resource')

@endsection
@section('content')
<section class="content-header">
<h1>
    Dashboard
    <small>Control panel</small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Manajemen Produk</a></li>
    <li class="active">Tambah Produk</li>
</ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                @component('components.card')
                    @slot('header')
                        Tambah Produk
                    @endslot

                    <div class="box-body">
                        <form action="{{ route('product.store') }}" role="form" method="POST" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <div class="box-body">
                                @include('components.error')
                                @if(session('error'))
                                    @component('components.alert', ['type' => 'danger'])
                                        {!! session('error') !!}
                                    @endcomponent
                                @endif
                                <div class="form-group">
                                    <label for="name">Kode Produk<sup>*</sup></label>
                                    <input type="text" name="code" id="code" required maxlength="10" 
                                    class="form-control {{ $errors->has('code') ? 'is-invalid' : '' }}" 
                                    placeholder="Masukan kode produk.." value="{{ old('code') }}">
                                    <p class="text-danger">{{ $errors->first('code') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="name">Nama Produk<sup>*</sup></label>
                                    <input type="text" name="name" id="name" required 
                                    class="form-control {{ $errors->has('code') ? 'is-invalid' : '' }}" 
                                    placeholder="Masukan nama produk.."
                                    value="{{ old('name') }}">
                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="description">Deskripsi</label>
                                    <textarea name="description" cols="5" rows="5" 
                                    class="form-control {{ $errors->has('code') ? 'is-invalid' : '' }}" 
                                    id="description" placeholder="Masukan deskripsi.."
                                    >{{ old('description') }}</textarea>
                                    <p class="text-danger">{{ $errors->first('description') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="stock">Stok<sup>*</sup></label>
                                    <input type="number" name="stock" id="stock" min="0" placeholder="0" required 
                                    class="form-control {{ $errors->has('stock') ? 'is-invalid' : '' }}" 
                                    value="{{ old('stock') }}">
                                    <p class="text-danger">{{ $errors->first('stock') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="price">Harga<sup>*</sup></label>
                                    <input type="number" name="price" id="price" required 
                                    class="form-control {{ $errors->has('price') ? 'is-invalid' : '' }}" 
                                    placeholder="Masukan harga.."
                                    value="{{ old('price') }}">
                                    <p class="text-danger">{{ $errors->first('price') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="category_id">Kategori<sup>*</sup></label>
                                    <select name="category_id" id="category_id" required
                                    class="form-control {{ $errors->has('category_id') ? 'is-invalid' : '' }}" >
                                        <option value="">Pilih</option>
                                        @foreach($categories as $row)
                                            <option value="{{ $row->id }}">{{ ucfirst($row->name) }}</option>
                                        @endforeach
                                    </select>
                                    <p class="text-danger">{{ $errors->first('category_id') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="price">Foto</label>
                                    <input type="file" name="photo" class="form-control">
                                    <p class="text-danger">{{ $errors->first('photo') }}</p>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-send"></i> Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box-body -->
                @endcomponent
            </div>
        </div>
    </div>
</section>
@endsection
@section('bottom-resource')
@endsection

resources/views/products/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit Produk')
@section('top-resource')

@endsection
@section('content')
<section class="content-header">
<h1>
    Dashboard
    <small>Control panel</small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Manajemen Produk</a></li>
    <li class="active">Edit Produk</li>
</ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                @component('components.card')
                    @slot('header')
                        Edit Produk
                    @endslot

                    <div class="box-body">
                        <form action="{{ route('product.update', $product->id) }}" role="form" method="POST" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <div class="box-body">
                                @include('components.error')
                                @if(session('error'))
                                    @component('components.alert', ['type' => 'danger'])
                                        {!! session('error') !!}
                                    @endcomponent
                                @endif
                                <div class="form-group">
                                    <label for="name">Kode Produk<sup>*</sup></label>
                                    <input type="text" name="code" id="code" required maxlength="10" 
                                    class="form-control {{ $errors->has('code') ? 'is-invalid' : '' }}" 
                                    value="{{ $product->code }}">
                                    <p class="text-danger">{{ $errors->first('code') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="name">Nama Produk<sup>*</sup></label>
                                    <input type="text" name="name" id="name" required 
                                    class="form-control {{ $errors->has('code') ? 'is-invalid' : '' }}" 
                                    value="{{ $product->name }}">
                                    <p class="text-danger">{{ $errors->first('code') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="description">Deskripsi</label>
                                    <textarea name="description" cols="5" rows="5" 
                                    class="form-control {{ $errors->has('code') ? 'is-invalid' : '' }}" 
                                    id="description">{{ $product->description }}</textarea>
                                    <p class="text-danger">{{ $errors->first('description') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="stock">Stok<sup>*</sup></label>
                                    <input type="number" name="stock" id="stock" min="0" placeholder="0" required 
                                    class="form-control {{ $errors->has('stock') ? 'is-invalid' : '' }}" 
                                    value="{{ $product->stock }}">
                                    <p class="text-danger">{{ $errors->first('stock') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="price">Harga<sup>*</sup></label>
                                    <input type="number" name="price" id="price" required 
                                    class="form-control {{ $errors->has('price') ? 'is-invalid' : '' }}" 
                                    value="{{ $product->price }}">
                                    <p class="text-danger">{{ $errors->first('price') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="category_id">Kategori<sup>*</sup></label>
                                    <select name="category_id" id="category_id" required
                                    class="form-control {{ $errors->has('category_id') ? 'is-invalid' : '' }}" >
                                        <option value="">Pilih</option>
                                        @foreach($categories as $row)
                                            <option value="{{ $row->id }}" 
                                                {{ $product->category_id == $row->id ? ' selected' : '' }}
                                                >{{ ucfirst($row->name) }}</option>
                                        @endforeach
                                    </select>
                                    <p class="text-danger">{{ $errors->first('category_id') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="price">Foto</label>
                                    <input type="file" name="photo" class="form-control">
                                    <p class="text-danger">{{ $errors->first('photo') }}</p>
                                    @if(!empty($product->photo))
                                        <img src="{{ asset('uploads/product/' . $product->photo) }}" 
                                        alt="{{ $product->name }}" width="150px" height="150px">
                                    @endif
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-refresh"></i> Update</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box-body -->
                @endcomponent
            </div>
        </div>
    </div>
</section>
@endsection
@section('bottom-resource')
@endsection

resources/views/products/index.blade.php
@extends('layouts.master')

@section('title', 'Tampilkan Product')
@section('top-resource')

@endsection
@section('content')
<section class="content-header">
<h1>
    Dashboard
    <small>Control panel</small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Manajemen Produk</a></li>
    <li class="active">Data Produk</li>
</ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                @component('components.card')
                    @slot('header')
                        <a href="{{ route('product.create') }}" class="btn btn-primary btn-sm">
                            <i class="fa fa-plus"></i> Tambah Produk</a>
                    @endslot

                    <div class="box-body">
                        @if(session('success'))
                            @component('components.alert', ['type' => 'success'])
                                {!! session('success') !!}
                            @endcomponent
                        @endif
                        <table id="example" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Gambar</th>
                                    <th>Nama Produk</th>
                                    <th>Stok</th>
                                    <th>Harga</th>
                                    <th>Kategori</th>
                                    <th>Last Update</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php $no = 1; @endphp
                                @forelse($products as $row)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>
                                            @if(!empty($row->photo))
                                                <img src="{{ asset('uploads/product/' . $row->photo) }}" 
                                                alt="{{ $row->name }}" width="50px" height="50px;">
                                            @else
                                                <img src="http://via.placeholder.com/50x50" alt="{{ $row->name }}">
                                            @endif
                                        </td>
                                        <td>
                                            <sup class="label label-success">{{ $row->code }}</sup>
                                            <strong>{{ $row->name }}</strong>
                                        </td>
                                        <td>{{ $row->stock }}</td>
                                        <td>Rp {{ number_format($row->price) }}</td>
                                        <td>{{ $row->category->name }}</td>
                                        <td>{{ $row->updated_at }}</td>
                                        <td>
                                            <form action="{{ route('product.destroy', $row->id) }}" method="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                <a href="{{ route('product.edit', $row->id) }}" class="btn btn-warning btn-sm"><i class="fa fa-edit"></i></a>
                                                <button class="btn btn-danger btn-sm">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form>    
                                        </td>                                        
                                    </tr>
                                @empty
                                    <p colspan="7" class="text-center">Tidak Ada Data</p>
                                @endforelse
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th>Gambar</th>
                                    <th>Nama Produk</th>
                                    <th>Stok</th>
                                    <th>Harga</th>
                                    <th>Kategori</th>
                                    <th>Last Update</th>
                                    <th>Aksi</th>
                                </tr>
                            </tfoot>
                        </table>
                        <div class="pull-right">
                            {!! $products->links() !!}
                        </div>
                    </div>
                    <!-- /.box-body -->
                @endcomponent
            </div>
        </div>
    </div>
</section>
@endsection
@section('bottom-resource')
@endsection